### ISSUE TITLE
Translations through Weblate locked

### ISSUE THREAD

**Issue by Anne017** [ubports/filemanager-app#4]
Hello,
For a week now, the translations through Weblate are locked for the filemanager-app.
Error message: "This translation is currently locked for updates!".
There is no such issue with the other core apps.
Is this weird or intentional?

**Comment by Flohack74** [comment]
This is intentional. Shortly after we loaded the filemanager app into Weblate we saw that there are at least 20 or 30 strings which are obsolete. Furthermore @sverzegnassi is working on a re-release. So it makes no sense to translate it right now. We will open it & announce in the forum as soon as we think its again good to go =)
