### ISSUE TITLE
"Unlock Full Access"

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/filemanager-app#6]
Will the "Unlock Full Access" be kept? I guess I never understood why the access to the SD card is protected by the root password... Maybe just the root folder can be protected with password. Or the "Unlock Full Access" can be kept but the file manager can remember the option in the settings that the access is unlocked.

**Comment by sverzegnassi** [comment]
Yes, that's going to be kept, but we're planning to improve both the UI and the policy in the next release (ETA is October).

- SD card access should not require any protection at all
- In the internal storage, only the Home folder should be accessible by default
- We'd like to remove the "Unlock Full access" action from the contextual menu, and show a descriptive empty state component with an "Unlock" button when the asked folder has actually a restricted access.

The password requirement (when full access is required) will stay untouched. However, in a longer term, we might remove this requirement if the "developer mode" has been enabled on the device. This way we could fit the needs of those developers who need to use seamlessly the advanced features of File Manager.

**Comment by mihaelmilea** [comment]
What about using the fingerprint instead of typing the passcode?: https://github.com/ubports/ubports-touch/issues/221

**Comment by nfsprodriver** [comment]
When this is included into the system, we may think about it )

**Comment by dobey** [comment]
Using the fingerprint instead of passcode will only work on systems with a fingerprint scanner, and when that is being used to unlock the phone.

The password entry in filemanager-app and terminal-app is by design because they have full access to read the filesystem, and requiring the password keeps someone else from accessing arbitrary files if you hand them your phone for a few seconds (assuming the app isn't already open and unlocked, of course). This is why the design has the password requirement there.

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/apps/filemanager-app/-/issues/6
